config/routes.rb
Rails.application.routes.draw do

  #トップページへのルーティング
  root to: 'toppages#index'

  #ユーザ新規登録
  get 'signup', to: 'users#new'
  
  #derstoyは後で。
  resources :users, only: [:show, :new, :create, :edit, :update]
  
  #セッション処理
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  
  #パスワード暗号化
  has_secure_password
  
  #バリデーション
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { in: 6..20 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  #ログイン要求
  def require_user_logged_in
    #ログインしていない場合は、ログイン画面へ移動
    unless logged_in?
      redirect_to login_url
    end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    
    email = params[:session][:email].downcase
    password = params[:session][:password]

    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #事前処理
  before_action :require_user_logged_in, only: [, :show]


  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create

    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end


  end

  def edit
  end

  def update
  end

  #Strong Paramter
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  #@current_user に既に現在のログインユーザが代入されていたら何もせず、代入されていなかったら User.find(...) からログインユーザを取得し、@current_user に代入する処理  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  #ユーザがログインしていれば true を返し、ログインしていなければ falseを返す
  def logged_in?
    !!current_user
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar fixed-top navbar-expand-sm navbar-light bg-light ">
    <a class="navbar-brand" href="/">It is my bike!</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'プロフィール', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to '新規登録', signup_path, class: 'nav-link' %>
          <%= link_to 'ログイン', login_path, class: 'nav-link' %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>It is my bike!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>It is my bike! ここに動画を貼る予定</h1>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>アカウント新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
    
      <!-- 登録に失敗した場合にエラーメッセージを表示 -->
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード(再入力)' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

        <%= f.submit '新規登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">

      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="#" class="nav-link">バイク１</a></li>
      <li class="nav-item"><a href="#" class="nav-link">フォロー</a></li>

    </ul>
  </div>
</div>